sonar.projectKey=guozichan_test
sonar.projectName=测试
sonar.organization=guozichan

sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.8,3.9,3.10,3.11

sonar.sourceEncoding=UTF-8
