sonar.projectKey=guozichan_test
sonar.projectName=EVA工具有
sonar.organization=guozichan

# 源代码位置
sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc

# Python版本
sonar.python.version=3.8,3.9,3.10,3.11

# 文件编码
sonar.sourceEncoding=UTF-8